
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was gdeflate-config.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

# gdeflate-config.cmake — generated by CMake
# Consumed by hipCOMP-core via:
#   set(ENV{gdeflate_ROOT} ${HIPCOMP_EXTS_ROOT})
#   find_package(gdeflate)
#   target_include_directories(hipcomp PRIVATE ${GDEFLATE_INCLUDE_DIRS})
#   target_link_libraries(hipcomp PRIVATE gdeflate)

include("${CMAKE_CURRENT_LIST_DIR}/gdeflate-targets.cmake")

# Set GDEFLATE_INCLUDE_DIRS for callers that use the old-style variable
get_target_property(_gdeflate_inc gdeflate::gdeflate INTERFACE_INCLUDE_DIRECTORIES)
set(GDEFLATE_INCLUDE_DIRS "${_gdeflate_inc}")

# Provide an unnamespaced alias so hipCOMP-core can write:
#   target_link_libraries(hipcomp PRIVATE gdeflate)
# CMake ALIAS targets cannot be used this way from external packages,
# so we create a plain imported INTERFACE target that wraps the real one.
if(NOT TARGET gdeflate)
    add_library(gdeflate INTERFACE IMPORTED)
    set_target_properties(gdeflate PROPERTIES
        INTERFACE_LINK_LIBRARIES "gdeflate::gdeflate"
    )
endif()

check_required_components(gdeflate)
