#include "cuda_runtime.h"
#if defined(__HIP_PLATFORM_NVCC__) || defined(__HIP_PLATFORM_NVIDIA__)
  #define hipDevAttrComputeCapabilityMajor cudaDevAttrComputeCapabilityMajor
  #define hipDeviceGetAttribute cudaDeviceGetAttribute
  #define hipDeviceProp_t cudaDeviceProp
  #define hipDeviceSynchronize cudaDeviceSynchronize
  #define hipErrorInvalidValue cudaErrorInvalidValue
  #define hipError_t cudaError_t
  #define hipEventCreate cudaEventCreate
  #define hipEventElapsedTime cudaEventElapsedTime
  #define hipEventRecord cudaEventRecord
  #define hipEvent_t cudaEvent_t
  #define hipFree cudaFree
  #define hipFreeAsync cudaFreeAsync
  #define hipGetDeviceProperties cudaGetDeviceProperties
  #define hipGetErrorString cudaGetErrorString
  #define hipGetLastError cudaGetLastError
  #define hipHostFree cudaFreeHost
  #define hipHostMalloc cudaMallocHost
  #define hipHostMallocDefault cudaHostAllocDefault
  #define hipMalloc cudaMalloc
  #define hipMallocAsync cudaMallocAsync
  #define hipMallocManaged cudaMallocManaged
  #define hipMemcpy cudaMemcpy
  #define hipMemcpyAsync cudaMemcpyAsync
  #define hipMemcpyDefault cudaMemcpyDefault
  #define hipMemcpyDeviceToDevice cudaMemcpyDeviceToDevice
  #define hipMemcpyDeviceToHost cudaMemcpyDeviceToHost
  #define hipMemcpyHostToDevice cudaMemcpyHostToDevice
  #define hipMemcpyKind cudaMemcpyKind
  #define hipMemoryTypeDevice cudaMemoryTypeDevice
  #define hipMemset cudaMemset
  #define hipMemsetAsync cudaMemsetAsync
  #define hipOccupancyMaxActiveBlocksPerMultiprocessor cudaOccupancyMaxActiveBlocksPerMultiprocessor
  #define hipPointerAttribute_t cudaPointerAttributes
  #define hipPointerGetAttributes cudaPointerGetAttributes
  #define hipRuntimeGetVersion cudaRuntimeGetVersion
  #define hipStreamCreate cudaStreamCreate
  #define hipStreamDestroy cudaStreamDestroy
  #define hipStreamSynchronize cudaStreamSynchronize
  #define hipStream_t cudaStream_t
  #define hipSuccess cudaSuccess
#endif
